import assert from 'node:assert/strict';
import { calculateQuoteBreakdown } from '../src/core.js';
import { QUOTATION_STATUS_TRANSITIONS, canTransitionQuotationStatus, createQuotationItemSnapshot, normalizeCustomerEntity, normalizeProductEntity, normalizeSearchText } from '../src/domain/entities.js';
import { hasQuotationItemDraftContent, validateQuotation } from '../src/domain/validation.js';
assert.deepEqual(calculateQuoteBreakdown({products:[{qty:2,price:100},{qty:3,price:50}],discountPct:10,vatPct:8,otherFee:25}),{subtotal:350,discountPct:10,discount:35,taxable:315,vatPct:8,vat:25.2,fee:25,total:365.2});
assert.equal(normalizeSearchText('  Tùng   Gia Bảo  '),'tung gia bao');
assert.equal(canTransitionQuotationStatus('draft','sent'),true);
assert.equal(canTransitionQuotationStatus('sent','accepted'),true);
assert.equal(canTransitionQuotationStatus('accepted','draft'),false);
assert.equal(canTransitionQuotationStatus('accepted','draft',{allowReopen:true}),true);
assert.deepEqual(QUOTATION_STATUS_TRANSITIONS.sent,['accepted','rejected','expired']);
const customer=normalizeCustomerEntity({id:'c1',name:'  An ',phone:'+84 912 345 678',company:'ABC'});
assert.equal(customer.customerId,'c1'); assert.equal(customer.name,'An'); assert.equal(customer.normalizedPhone,'84912345678'); assert.equal(customer.type,'company');
const product=normalizeProductEntity({id:'p1',name:' Hàng A ',price:'12000',currency:'usd'});
assert.equal(product.productId,'p1'); assert.equal(product.defaultPrice,12000); assert.equal(product.currency,'USD');
const item=createQuotationItemSnapshot(product,{itemId:'item-1'});
assert.equal(item.itemId,'item-1'); assert.equal(item.sourceProductId,'p1'); assert.equal(item.nameSnapshot,'Hàng A'); assert.equal(item.price,12000);
assert.equal(hasQuotationItemDraftContent({name:'',qty:1,price:0}),false);
assert.equal(hasQuotationItemDraftContent({name:'',qty:2,price:0}),true);
const invalid=validateQuotation({companyName:'',quoteTitle:'',quoteStatus:'sent',quoteDate:'2026-02-30',quoteNo:'',products:[{name:'',qty:2,price:0}]});
assert.ok(invalid.errors.includes('Thiếu tên công ty.')); assert.ok(invalid.errors.includes('Thiếu tiêu đề báo giá.'));
assert.ok(invalid.errors.some(x=>x.includes('chưa có số báo giá'))); assert.ok(invalid.errors.some(x=>x.includes('Ngày báo giá không hợp lệ'))); assert.ok(invalid.errors.some(x=>x.includes('chưa có tên')));
const warning=validateQuotation({companyName:'TGB',quoteTitle:'BẢNG BÁO GIÁ',quoteStatus:'draft',products:[{name:'Hàng A',qty:1,price:0}],showPrice:true});
assert.ok(warning.warnings.some(x=>x.includes('chưa có đơn giá')));
console.log('DOMAIN MODEL / VALIDATION PASS');
