const $=(id)=>document.getElementById(id);
const STORAGE='price-report:tunggiabao:v1';
const clone=(x)=>JSON.parse(JSON.stringify(x));
const esc=(v)=>{const n=document.createElement('span');n.textContent=String(v??'');return n.innerHTML};
const today=()=>new Date().toISOString().slice(0,10);
const defaults={
 company:{brandName:'THẾ GIỚI TRỨNG®',name:'CÔNG TY TNHH TMDV BIỂN UYÊN BẢO',address:'12/1 đường 3/4, Phường Xuân Hương - Đà Lạt, Lâm Đồng',branchKhanhHoa:'Số 55 Nguyễn Xiển, P Bắc Nha Trang, Khánh Hòa',branchDongNai:'Tổ 8, Khu phố 3A, Phường Trảng Dài, Đồng Nai',farm:'Ấp Bàu Mây, Xã Tân Phú, Tỉnh Đồng Nai',taxCode:'5801476262',phone:'0888.458.222',website:'www.thegioitrung.vn',email:'contact@thegioitrung.vn',slogan:'Foods for health'},
 customer:{name:'QUÝ KHÁCH HÀNG',company:'',address:'',phone:'',email:'',contact:''},
 quote:{title:'BẢNG BÁO GIÁ',number:'BG-2026-001',date:today(),validity:'7 ngày',recipient:'Kính gửi: QUÝ KHÁCH HÀNG',intro:'Công ty TNHH TM DV Biển Uyên Bảo xin trân trọng gửi đến Quý khách hàng bảng báo giá sản phẩm của chúng tôi như sau:',section:'I. CÁC SẢN PHẨM TRỨNG'},
 products:[{name:'Trứng gà tươi',pack:'Hộp 10 quả',unit:'Hộp',qty:100,price:28000,note:''},{name:'Trứng gà Omega-3',pack:'Hộp 10 quả',unit:'Hộp',qty:50,price:32000,note:''},{name:'Trứng vịt tươi',pack:'Hộp 10 quả',unit:'Hộp',qty:50,price:30000,note:''}],
 finance:{discountPct:0,vatPct:0,otherFee:0,currency:'VND',paymentMethod:'Tiền mặt hoặc chuyển khoản',bankName:'',bankAccount:'',bankOwner:''},
 terms:{title:'II. ĐIỀU KHOẢN THƯƠNG MẠI',text:'Giá trên đã bao gồm VAT (nếu có), chi phí giao hàng tùy theo khu vực.\nThời gian giao hàng: 1 - 3 ngày kể từ khi xác nhận đơn hàng.\nPhương thức thanh toán: Tiền mặt hoặc chuyển khoản.\nBảng báo giá có hiệu lực trong vòng 7 ngày kể từ ngày phát hành.',closing:'Rất mong được hợp tác cùng Quý khách hàng!'},
 signature:{dateLine:'Đà Lạt, ngày ..... tháng ..... năm ........',leftTitle:'KHÁCH HÀNG',rightTitle:'ĐẠI DIỆN CÔNG TY',leftNote:'(Ký, ghi rõ họ tên)',rightNote:'(Ký, ghi rõ họ tên, đóng dấu)',leftName:'',rightName:''},
 display:{theme:'modern',accent:'#0b8f83',font:'Times New Roman',fontSize:12.2,marginX:13,marginTop:13,marginBottom:12,logoWidth:61,showLogo:true,showCustomer:false,showWeb:true,showTerms:true,showSignature:true,showStt:true,showPrice:true,showAmount:true,showNote:false,showTotals:true,showWords:true,compact:false},
 footer:'Vì sức khỏe cộng đồng  •  0888.458.222  •  contact@thegioitrung.vn  •  www.thegioitrung.vn',logo:''
};
function merge(x={}){return {...clone(defaults),...x,company:{...defaults.company,...(x.company||{})},customer:{...defaults.customer,...(x.customer||{})},quote:{...defaults.quote,...(x.quote||{})},finance:{...defaults.finance,...(x.finance||{})},terms:{...defaults.terms,...(x.terms||{})},signature:{...defaults.signature,...(x.signature||{})},display:{...defaults.display,...(x.display||{})},products:Array.isArray(x.products)?x.products:clone(defaults.products)}}
let state=(()=>{try{return merge(JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{return merge()}})();
let zoom=82;
const get=(path)=>path.split('.').reduce((o,k)=>o?.[k],state);
function set(path,value){const p=path.split('.');let o=state;for(let i=0;i<p.length-1;i++)o=o[p[i]];o[p.at(-1)]=value;save();render()}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function number(v){const n=Number(v);return Number.isFinite(n)?n:0}
function money(v){const cur=state.finance.currency,d=cur==='VND'?0:2;return new Intl.NumberFormat('vi-VN',{minimumFractionDigits:d,maximumFractionDigits:d}).format(number(v))+' '+cur}
function totals(){const subtotal=state.products.reduce((s,p)=>s+number(p.qty)*number(p.price),0),discount=subtotal*number(state.finance.discountPct)/100,taxable=subtotal-discount,vat=taxable*number(state.finance.vatPct)/100,fee=number(state.finance.otherFee);return{subtotal,discount,vat,fee,total:taxable+vat+fee}}
const digits=['không','một','hai','ba','bốn','năm','sáu','bảy','tám','chín'];
function r3(n,full){const h=Math.floor(n/100),t=Math.floor((n%100)/10),u=n%10;let s='';if(h||full){s+=digits[h]+' trăm';if(!t&&u)s+=' lẻ'}if(t>1){s+=(s?' ':'')+digits[t]+' mươi';if(u===1)s+=' mốt';else if(u===5)s+=' lăm';else if(u)s+=' '+digits[u]}else if(t===1){s+=(s?' ':'')+'mười';if(u===5)s+=' lăm';else if(u)s+=' '+digits[u]}else if(u)s+=(s?' ':'')+digits[u];return s}
function words(v){let n=Math.round(number(v));if(n===0)return'Không';const scales=['','nghìn','triệu','tỷ','nghìn tỷ','triệu tỷ'],g=[];while(n){g.push(n%1000);n=Math.floor(n/1000)}const p=[];for(let i=g.length-1;i>=0;i--){if(!g[i])continue;p.push(r3(g[i],i<g.length-1&&g[i]<100)+(scales[i]?' '+scales[i]:''))}const s=p.join(' ').replace(/\s+/g,' ');return s.charAt(0).toUpperCase()+s.slice(1)}
function dateVN(v){if(!v)return'';const p=v.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v}
const configs={
 company:[['Tên thương hiệu','company.brandName'],['Tên công ty','company.name'],['Địa chỉ trụ sở','company.address'],['Chi nhánh Khánh Hòa','company.branchKhanhHoa'],['Chi nhánh Đồng Nai','company.branchDongNai'],['Trại / cơ sở','company.farm'],['MST','company.taxCode'],['SĐT','company.phone'],['Website','company.website'],['Email','company.email','email'],['Slogan','company.slogan']],
 quote:[['Tiêu đề','quote.title'],['Số báo giá','quote.number'],['Ngày báo giá','quote.date','date'],['Hiệu lực','quote.validity'],['Kính gửi','quote.recipient'],['Lời mở đầu','quote.intro','textarea'],['Tiêu đề nhóm sản phẩm','quote.section']],
 customer:[['Tên khách hàng','customer.name'],['Công ty / đơn vị','customer.company'],['Địa chỉ','customer.address'],['SĐT','customer.phone'],['Email','customer.email','email'],['Người liên hệ','customer.contact']],
 finance:[['Giảm giá (%)','finance.discountPct','number'],['VAT (%)','finance.vatPct','number'],['Phí khác','finance.otherFee','number'],['Tiền tệ','finance.currency','select',['VND','USD','RUB']]],
 bank:[['Phương thức','finance.paymentMethod'],['Ngân hàng','finance.bankName'],['Số tài khoản','finance.bankAccount'],['Chủ tài khoản','finance.bankOwner']],
 signature:[['Dòng ngày tháng','signature.dateLine'],['Chức danh bên trái','signature.leftTitle'],['Chức danh bên phải','signature.rightTitle'],['Ghi chú bên trái','signature.leftNote'],['Ghi chú bên phải','signature.rightNote'],['Họ tên bên trái','signature.leftName'],['Họ tên bên phải','signature.rightName'],['Chân trang','footer','textarea']],
 layout:[['Font chữ','display.font','select',['Times New Roman','Georgia','Arial']],['Cỡ chữ (px)','display.fontSize','number'],['Lề ngang (mm)','display.marginX','number'],['Lề trên (mm)','display.marginTop','number'],['Lề dưới (mm)','display.marginBottom','number'],['Rộng logo (mm)','display.logoWidth','number']]
};
function fieldNode(cfg){const [label,path,type='text',choices]=cfg,w=document.createElement('div');w.className='field';const l=document.createElement('label');l.textContent=label;let input;if(type==='textarea')input=document.createElement('textarea');else if(type==='select'){input=document.createElement('select');choices.forEach(c=>{const op=document.createElement('option');op.value=c;op.textContent=c;input.appendChild(op)})}else{input=document.createElement('input');input.type=type}input.value=get(path)??'';input.dataset.path=path;input.oninput=()=>set(path,type==='number'?number(input.value):input.value);input.onchange=input.oninput;w.append(l,input);return w}
function fill(id,list){const r=$(id);r.innerHTML='';list.forEach(c=>r.appendChild(fieldNode(c)))}
function toggleNode(label,path){const row=document.createElement('div');row.className='switch-row';const span=document.createElement('span');span.textContent=label;const lab=document.createElement('label');lab.className='switch';const i=document.createElement('input');i.type='checkbox';i.checked=!!get(path);i.onchange=()=>set(path,i.checked);lab.append(i,document.createElement('i'));row.append(span,lab);return row}
function buildToggles(){const r=$('displayToggles');r.innerHTML='';[['Hiện logo','display.showLogo'],['Hiện STT','display.showStt'],['Hiện đơn giá','display.showPrice'],['Hiện thành tiền','display.showAmount'],['Hiện ghi chú','display.showNote'],['Hiện tổng cộng','display.showTotals'],['Hiện số tiền bằng chữ','display.showWords'],['Hiện khách hàng chi tiết','display.showCustomer'],['Hiện website/email','display.showWeb'],['Hiện điều khoản','display.showTerms'],['Hiện chữ ký','display.showSignature'],['Bảng thu gọn','display.compact']].forEach(x=>r.appendChild(toggleNode(x[0],x[1])))}
function buildTerms(){const r=$('termsForm');r.innerHTML='';r.append(fieldNode(['Tiêu đề','terms.title']));const w=fieldNode(['Mỗi dòng = 1 điều khoản','terms.text','textarea']);r.append(w);r.append(fieldNode(['Lời kết','terms.closing']))}
function buildProducts(){const r=$('productEditor');let html='<table><thead><tr><th>#</th><th>Tên sản phẩm</th><th>Quy cách</th><th>ĐVT</th><th>SL</th><th>Đơn giá</th><th>Ghi chú</th><th></th></tr></thead><tbody>';state.products.forEach((p,i)=>{html+='<tr data-i="'+i+'"><td>'+(i+1)+'</td>';['name','pack','unit','qty','price','note'].forEach(k=>{html+='<td><input data-k="'+k+'" type="'+(['qty','price'].includes(k)?'number':'text')+'" value="'+esc(p[k])+'"></td>'});html+='<td><button class="btn danger" data-del="'+i+'">Xóa</button></td></tr>'});html+='</tbody></table>';r.innerHTML=html;r.querySelectorAll('input').forEach(input=>input.oninput=()=>{const tr=input.closest('tr'),i=Number(tr.dataset.i),k=input.dataset.k;state.products[i][k]=['qty','price'].includes(k)?number(input.value):input.value;save();render()});r.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.products.splice(Number(b.dataset.del),1);save();buildProducts();render()})}
function buildDesign(){const themes=[['modern','Hiện đại'],['classic','Cổ điển'],['minimal','Tối giản'],['blue','Mẫu màu']],r=$('templateGrid');r.innerHTML='';themes.forEach(t=>{const b=document.createElement('button');b.className='template'+(state.display.theme===t[0]?' active':'');b.innerHTML='<div class="template-thumb '+t[0]+'"></div><div class="template-name">'+t[1]+'</div>';b.onclick=()=>{state.display.theme=t[0];save();buildDesign();render()};r.appendChild(b)});const colors=['#0b8f83','#1774db','#f39c12','#e83e3e','#7a4ae2','#263444'],c=$('colorGrid');c.innerHTML='';colors.forEach(x=>{const b=document.createElement('button');b.className='color'+(state.display.accent===x?' active':'');b.style.background=x;b.onclick=()=>{state.display.accent=x;save();buildDesign();render()};c.appendChild(b)})}
function buildAll(){fill('companyForm',configs.company);fill('quoteForm',configs.quote);fill('customerForm',configs.customer);fill('financeForm',configs.finance);fill('bankForm',configs.bank);fill('signatureForm',configs.signature);fill('layoutForm',configs.layout);buildTerms();buildToggles();buildProducts();buildDesign()}
function render(){const d=state.display,p=$('paper');p.className='paper theme-'+d.theme;p.style.setProperty('--doc-accent',d.accent);p.style.padding=d.marginTop+'mm '+d.marginX+'mm '+d.marginBottom+'mm';p.style.fontFamily='"'+d.font+'",serif';p.style.fontSize=d.fontSize+'px';renderBrand();renderCompany();$('docTitle').textContent=state.quote.title;$('docRecipient').textContent=state.quote.recipient;$('docMeta').innerHTML='<div><b>Số báo giá:</b> '+esc(state.quote.number)+'</div><div><b>Ngày báo giá:</b> '+esc(dateVN(state.quote.date))+'</div><div><b>Hiệu lực:</b> '+esc(state.quote.validity)+'</div>';$('docIntro').textContent=state.quote.intro;$('docSection').textContent=state.quote.section;const cb=[state.customer.name,state.customer.company,state.customer.address,state.customer.phone,state.customer.email].filter(Boolean).join(' • ');$('customerBox').textContent=cb;$('customerBox').style.display=d.showCustomer&&cb?'block':'none';renderTable();renderTotals();renderTerms();renderSignatures();$('docFooter').textContent=state.footer;applyZoom(zoom)}
function renderBrand(){const r=$('docBrand');if(!state.display.showLogo){r.innerHTML='';return}if(state.logo){r.innerHTML='<img src="'+state.logo+'" alt="Logo" style="width:'+state.display.logoWidth+'mm">'}else r.innerHTML='<div class="wordmark"><b>'+esc(state.company.brandName)+'</b><small>'+esc(state.company.slogan)+'</small></div>'}
function renderCompany(){const c=state.company,rows=[['Trụ sở',c.address],['CN Khánh Hòa',c.branchKhanhHoa],['CN Đồng Nai',c.branchDongNai],['Trại',c.farm],['MST',c.taxCode],['SĐT',c.phone]];if(state.display.showWeb){rows.push(['Website',c.website],['Email',c.email])}$('companyCopy').innerHTML='<h3>'+esc(c.name)+'</h3>'+rows.map(x=>'<p><b>'+esc(x[0])+':</b> '+esc(x[1])+'</p>').join('')}
function renderTable(){const d=state.display,cols=[];if(d.showStt)cols.push(['STT','stt']);cols.push(['Tên sản phẩm','name'],['Quy cách','pack'],['ĐVT','unit'],['Số lượng','qty']);if(d.showPrice)cols.push(['Đơn giá ('+state.finance.currency+')','price']);if(d.showAmount)cols.push(['Thành tiền ('+state.finance.currency+')','amount']);if(d.showNote)cols.push(['Ghi chú','note']);$('quoteHead').innerHTML='<tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr>';$('quoteBody').innerHTML=state.products.map((p,i)=>'<tr>'+cols.map(c=>{const k=c[1];let v=k==='stt'?i+1:k==='price'?money(p.price):k==='amount'?money(number(p.qty)*number(p.price)):p[k]??'';const cls=['stt','unit','qty'].includes(k)?'center':['price','amount'].includes(k)?'num':'';return '<td class="'+cls+'">'+esc(v)+'</td>'}).join('')+'</tr>').join('');document.querySelectorAll('.quote-table th,.quote-table td').forEach(el=>el.style.padding=d.compact?'1.1mm 1mm':'2mm 1.4mm')}
function renderTotals(){const t=totals(),rows=[['Tạm tính',t.subtotal,''],...(t.discount?[['Giảm giá',-t.discount,'']]:[]),...(t.vat?[['VAT',t.vat,'']]:[]),...(t.fee?[['Phí khác',t.fee,'']]:[]),['Tổng cộng',t.total,'grand']];$('totals').innerHTML=rows.map(x=>'<tr><td class="'+x[2]+'">'+esc(x[0])+'</td><td class="'+x[2]+'">'+esc(money(x[1]))+'</td></tr>').join('');$('totals').style.display=state.display.showTotals&&state.display.showAmount?'table':'none';$('words').textContent='Bằng chữ: '+words(t.total)+' đồng.';$('words').style.display=state.display.showWords&&state.display.showTotals&&state.display.showAmount&&state.finance.currency==='VND'?'block':'none'}
function renderTerms(){$('docTermsTitle').textContent=state.terms.title;$('termsList').innerHTML=state.terms.text.split(/\n+/).filter(Boolean).map(x=>'<li>'+esc(x)+'</li>').join('');$('closing').textContent=state.terms.closing;$('docTerms').style.display=state.display.showTerms?'block':'none'}
function renderSignatures(){const s=state.signature,one=(title,note,name)=>'<div><div class="sig-date">'+esc(s.dateLine)+'</div><div class="sig-title">'+esc(title)+'</div><div class="sig-note">'+esc(note)+'</div><div class="sig-name">'+esc(name)+'</div></div>';$('signatures').innerHTML=one(s.leftTitle,s.leftNote,s.leftName)+one(s.rightTitle,s.rightNote,s.rightName);$('signatures').style.display=state.display.showSignature?'grid':'none'}
const tabMeta={general:['THÔNG TIN CHUNG','Doanh nghiệp và dữ liệu báo giá.'],customer:['KHÁCH HÀNG','Thông tin người nhận và đơn vị mua hàng.'],products:['SẢN PHẨM','Danh mục, số lượng và đơn giá.'],finance:['THANH TOÁN','Chiết khấu, VAT và tài khoản.'],terms:['ĐIỀU KHOẢN','Điều khoản thương mại và chữ ký.'],design:['THIẾT KẾ','Template, màu sắc và định dạng A4.'],export:['XUẤT / IN','PDF và sao lưu dữ liệu.']};
function tab(name){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id==='tab-'+name));$('tabTitle').textContent=tabMeta[name][0];$('tabSub').textContent=tabMeta[name][1]}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
$('addProduct').onclick=()=>{state.products.push({name:'',pack:'',unit:'',qty:1,price:0,note:''});save();buildProducts();render()};
$('logoInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.logo=String(r.result);save();syncBrand();render()};r.readAsDataURL(f);e.target.value=''};$('clearLogo').onclick=()=>{state.logo='';save();syncBrand();render()};
function syncBrand(){$('brandPreview').innerHTML=state.logo?'<img src="'+state.logo+'" alt="Logo"><div><b>'+esc(state.company.name)+'</b><small>'+esc(state.company.slogan)+'</small></div>':'<img src="./assets/icon.svg" alt=""><div><b>'+esc(state.company.brandName)+'</b><small>'+esc(state.company.slogan)+'</small></div>'}
function download(name,text,type){const blob=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('exportJson').onclick=()=>download('bao-gia-du-lieu.json',JSON.stringify(state,null,2),'application/json');$('importJson').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=merge(JSON.parse(r.result));save();buildAll();syncBrand();render()}catch{alert('File JSON không hợp lệ.')}};r.readAsText(f,'utf-8');e.target.value=''};$('resetBtn').onclick=()=>{if(confirm('Khôi phục toàn bộ dữ liệu mẫu?')){state=merge();save();buildAll();syncBrand();render()}};
$('printBtn').onclick=()=>window.print();$('printTopBtn').onclick=()=>window.print();
function applyZoom(v){zoom=Math.max(50,Math.min(120,v));$('paperScale').style.transform='scale('+(zoom/100)+')';$('zoomText').textContent=zoom+'%';$('paperScale').style.marginBottom=((zoom/100-1)*$('paper').offsetHeight)+'px'}function fit(){applyZoom(Math.floor(( $('canvas').clientWidth-36 )/$('paper').offsetWidth*100))}$('fitBtn').onclick=fit;$('actualBtn').onclick=()=>applyZoom(100);window.onresize=()=>{if(innerWidth>900)fit()};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
buildAll();syncBrand();render();setTimeout(fit,60);
