name: Webapp CI

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "webapp/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: npm install
      - run: npm audit --omit=dev --audit-level=high
      - run: npm test
      - run: npm run build
